# Generated by Django 3.1 on 2020-08-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='description',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
